# -*- coding: utf-8 -*-
"""EjerciciosPandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12N3ie6k7a6v421ZQbfljlJeAhRiNfPh1
"""

mylist = list('abcdefghijklmnopqrstuvwxyz')

len(mylist)

ser1 = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

import pandas as pd

import numpy as np

#Combinar dos series en una

ser1 = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
serConcat = pd.concat([ser1, ser2], axis=1)

serConcat

#Hacer la primera letra mayúscula
lista_palabras = ["hola", "ola", "bonjour"]
lista_palabras_dataframe = pd.DataFrame(lista_palabras)
lista_palabras_dataframe.apply(lambda x : x.str.capitalize())

#filtrar elementos que no esten en un series
ser1 = pd.Series([1,2,3,4,5])
ser2 = pd.Series([4,5,6,7,8])
ser1.isin(ser2)

ser1[ser1.isin(ser2)]

#arr a dtafarame
my_ser = np.random.randint(1,10,35)

my_ser

my_ser = np.resize(my_ser, (7,5))

my_ser

#calcular distancia euclideana
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
result = np.sqrt(np.sum((a-b)**2))
result
a_pd = pd.Series([1,2,3,4,5])
b_pd = pd.Series([4,5,6,7,8])

(((a_pd - b_pd) ** 2).sum()) ** (1/2)

